### ISSUE TITLE
Deposit wEth amount smaller or equal with -4973

### ISSUE THREAD

**Issue by danlex** [Equalizer-Finance/equalizer-issues#2]
When I try to deposit 1 eth there is a message error displayed:
Please provide an amount smaller or equal with -4973.166995227565523935

The error appears when the max capacity is lower than deposited amount.

<img width="2038" alt="Screenshot 2021-08-04 at 11 41 31" src="https://user-images.githubusercontent.com/1996653/128151377-0b918225-9416-44f2-b920-aae74470b6b1.png">

**Comment by gabrielavictoriabr** [comment]
The fix should also include the Deposit Max value, not only the text message when the deposit value is added using the edit box
👍 
![image](https://user-images.githubusercontent.com/87069641/128198458-eb316a75-fa4c-4d22-96f0-18666cd89a45.png)

**Comment by tom1145** [comment]
> The fix should also include the Deposit Max value, not only the text message when the deposit value is added using the edit box
> 👍
> ![image](https://user-images.githubusercontent.com/87069641/128198458-eb316a75-fa4c-4d22-96f0-18666cd89a45.png)

Thanks for letting me know! 💯 I will fix this now! :D
