### ISSUE TITLE
Header overlapping on Hero bar chart whn browser zoom is increased without possibility to use the browser vertical scroll bar

### ISSUE THREAD

**Issue by gabrielavictoriabr** [Equalizer-Finance/equalizer-issues#7]
When browser zoom is increased, the browser scroll bar is limited to the header zone and the Hero bar chart  is not seen anymore

![image](https://user-images.githubusercontent.com/87069641/127448299-9bf09cac-0979-4b8a-a021-9427d03bf9da.png)

**Comment by litium1000** [comment]
Not applicable after changing the location for the text in header
